import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/footer/Footer";

export const metadata: Metadata = {
    title: "Galaxy Dental Clinic",
    description: "Generated by create next app"
};

const manrope = Manrope({ subsets: ["latin"] });

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <html lang="en">
        <body className={manrope.className}>
            <Header/>
            {children}
            <Footer/>
        </body>
    </html>
}
